"""Confirmed Storm & Me / Will Scott book catalog."""


def amazon_cover(asin: str) -> str:
    return f"https://images-na.ssl-images-amazon.com/images/P/{asin}.01.LZZZZZZZ.jpg"


BOOKS = [
    {
        'id': 'the-storm-in-me',
        'title': 'The Storm in Me',
        'subtitle': 'The Man Who Refused to Stay Broken',
        'category': 'Healing & Personal Growth',
        'categories': ['Healing & Personal Growth', 'Personal Growth', 'Featured'],
        'price': 0.0,
        'formats': ['Amazon'],
        'cover': amazon_cover("B0GSVSSXP8"),
        'summary': 'A deeply personal story about surviving the storm, rebuilding a life, and refusing to let brokenness have the final word.',
        'description': 'The Storm in Me is a testimony of endurance, healing, and the stubborn decision to keep standing when life says stay down.',
        'author_note': 'This is the heart of the Storm & Me mission. — Will Scott',
        'amazon_link': 'https://www.amazon.com/Storm-Me-Refused-Stay-Broken/dp/B0GSVSSXP8',
        'trailer_url': '',
        'status': 'featured',
        'reviews': [],
        'related': ['quiet-battles', '365-days-fearless-faith', 'no-ones-coming-to-save-you'],
    },
    {
        'id': '365-days-fearless-faith',
        'title': '365 Days of Fearless Faith',
        'subtitle': 'Daily Devotions for Anxious Hearts',
        'category': 'Faith & Encouragement',
        'categories': ['Healing & Personal Growth', 'Faith & Encouragement'],
        'price': 0.0,
        'formats': ['Kindle', 'Amazon'],
        'cover': amazon_cover("B0GX2WYVZF"),
        'summary': 'A full year of daily encouragement for anxious hearts learning to choose faith one day at a time.',
        'description': 'Short, approachable devotionals designed to bring calm, courage, and perspective into everyday life.',
        'author_note': 'Faith does not always remove the fear. Sometimes it teaches us how to walk through it. — Will Scott',
        'amazon_link': 'https://www.amazon.com/365-Days-Fearless-Faith-Anxious-ebook/dp/B0GX2WYVZF',
        'trailer_url': '',
        'status': 'available',
        'reviews': [],
        'related': ['the-storm-in-me', 'quiet-battles', 'no-ones-coming-to-save-you'],
    },
    {
        'id': 'quiet-battles',
        'title': 'Quiet Battles',
        'subtitle': 'Silent Struggles Within',
        'category': 'Healing & Personal Growth',
        'categories': ['Healing & Personal Growth', 'Mental Health'],
        'price': 0.0,
        'formats': ['Amazon'],
        'cover': amazon_cover("B0H2PN618X"),
        'summary': 'For the people fighting battles nobody else can see—and still finding a reason to rise.',
        'description': 'Quiet Battles gives language to the private pain, hidden pressure, and unseen victories that shape so many lives.',
        'author_note': 'Some of the hardest battles make no sound. — Will Scott',
        'amazon_link': 'https://www.amazon.com/Quiet-Battles-Silent-Struggles-Within/dp/B0H2PN618X',
        'trailer_url': '',
        'status': 'available',
        'reviews': [],
        'related': ['the-storm-in-me', '365-days-fearless-faith', 'no-ones-coming-to-save-you'],
    },
    {
        'id': 'no-ones-coming-to-save-you',
        'title': "No One's Coming to Save You",
        'subtitle': 'The moment you stop waiting is the moment your life can change',
        'category': 'Healing & Personal Growth',
        'categories': ['Healing & Personal Growth', 'Personal Growth'],
        'price': 0.0,
        'formats': ['Kindle', 'Amazon'],
        'cover': amazon_cover("B0H29LRTF2"),
        'summary': 'A direct, honest push toward ownership, courage, and rebuilding your own life.',
        'description': 'A practical and unfiltered reminder that change begins when waiting ends and action starts.',
        'author_note': 'Not hopeless—empowering. The power to begin is already yours. — Will Scott',
        'amazon_link': 'https://www.amazon.com/No-Ones-Coming-Save-You-ebook/dp/B0H29LRTF2',
        'trailer_url': '',
        'status': 'available',
        'reviews': [],
        'related': ['the-storm-in-me', 'quiet-battles', 'laid-off-handbook'],
    },
    {
        'id': 'laid-off-handbook',
        'title': "Laid Off: A Person's Handbook",
        'subtitle': 'When the job disappears, your story does not have to',
        'category': 'Career & Life',
        'categories': ['Career & Life', 'Healing & Personal Growth'],
        'price': 0.0,
        'formats': ['Amazon'],
        'cover': amazon_cover("B0H6HK5TTX"),
        'summary': 'A grounded guide for the shock, fear, identity loss, and new beginning that can follow a layoff.',
        'description': 'Part survival guide and part encouragement, this handbook helps readers steady themselves and begin again after job loss.',
        'author_note': 'Losing the job is an event. It does not get to become your identity. — Will Scott',
        'amazon_link': 'https://www.amazon.com/Laid-Off-Persons-Handbook-Disappears/dp/B0H6HK5TTX',
        'trailer_url': '',
        'status': 'available',
        'reviews': [],
        'related': ['no-ones-coming-to-save-you', 'the-storm-in-me'],
    },
    {
        'id': 'let-it-go-little-doll',
        'title': 'Let It Go, Little Doll',
        'subtitle': 'A gentle story for young hearts learning to release what hurts',
        'category': "Children's Books",
        'categories': ["Children's Books", 'Emotional Healing', 'The Let It Go Series'],
        'price': 0.0,
        'formats': ['Amazon'],
        'cover': amazon_cover("B0H88BR82Y"),
        'summary': 'A tender coming-of-age story about big feelings, healing, and learning when to let go.',
        'description': 'Created for children carrying feelings they may not yet know how to name, this story offers comfort without pretending the hurt was never real.',
        'author_note': 'For every young heart learning that letting go is not the same as forgetting. — Will Scott',
        'amazon_link': 'https://www.amazon.com/Let-Go-Little-Doll/dp/B0H88BR82Y',
        'trailer_url': '',
        'status': 'new',
        'series_order': 1,
        'reviews': [],
        'related': ['let-it-go-little-bear', 'let-it-go-little-bear-deluxe'],
    },
    {
        'id': 'last-block-book-one',
        'title': 'The Last Block on Earth',
        'subtitle': 'Book One',
        'category': 'Science Fiction',
        'categories': ['Science Fiction', 'The Last Block on Earth Series'],
        'price': 0.0,
        'formats': ['Amazon'],
        'cover': amazon_cover("B0GZVH718V"),
        'summary': 'The beginning of a survival story where one remaining block may hold the future of everything.',
        'description': 'Book One launches The Last Block on Earth series and introduces the world, the danger, and the impossible choices ahead.',
        'author_note': 'Start here before entering Mercy Node. — Will Scott',
        'amazon_link': 'https://www.amazon.com/Last-Block-Earth-Will-Scott/dp/B0GZVH718V',
        'trailer_url': '',
        'status': 'available',
        'series_order': 1,
        'reviews': [],
        'related': ['last-block-mercy-node'],
    },
    {
        'id': 'last-block-mercy-node',
        'title': 'The Last Block on Earth: Mercy Node',
        'subtitle': 'Book Two',
        'category': 'Science Fiction',
        'categories': ['Science Fiction', 'The Last Block on Earth Series'],
        'price': 0.0,
        'formats': ['Kindle', 'Amazon'],
        'cover': amazon_cover("B0H6KX6YZ1"),
        'summary': 'The world of The Last Block expands as Mercy Node raises the stakes in Book Two.',
        'description': 'The second installment continues the series with new danger, deeper mysteries, and consequences born from Book One.',
        'author_note': 'Read The Last Block on Earth first for the full journey. — Will Scott',
        'amazon_link': 'https://www.amazon.com/Last-Block-Earth-Mercy-Node-ebook/dp/B0H6KX6YZ1',
        'trailer_url': '',
        'status': 'new',
        'series_order': 2,
        'reviews': [],
        'related': ['last-block-book-one'],
    },
    {
        'id': 'abductee-chronicles-marcus',
        'title': 'The Abductee Chronicles',
        'subtitle': 'Book One — The Abduction of Marcus',
        'category': 'Science Fiction',
        'categories': ['Science Fiction', 'The Abductee Chronicles'],
        'price': 0.0,
        'formats': ['Kindle', 'Amazon'],
        'cover': amazon_cover("B0GYJWVM5L"),
        'summary': 'Marcus disappears—and the truth waiting beyond the ordinary world is stranger than anyone imagined.',
        'description': 'Book One of The Abductee Chronicles begins a suspenseful science-fiction journey centered on Marcus and the mystery of his abduction.',
        'author_note': 'Some disappearances are only the beginning. — Will Scott',
        'amazon_link': 'https://www.amazon.com/Abductee-Chronicles-Book-Abduction-Marcus-ebook/dp/B0GYJWVM5L',
        'trailer_url': '',
        'status': 'available',
        'reviews': [],
        'related': ['last-block-book-one', 'last-block-mercy-node'],
    },
    {
        'id': 'let-it-go-little-bear',
        'title': 'Let It Go, Little Bear',
        'subtitle': 'Storybook Edition — Black & White',
        'category': "Children's Books",
        'categories': ["Children's Books", 'Emotional Healing', 'The Let It Go Series'],
        'price': 0.0,
        'formats': ['Paperback', 'Black & White', 'Amazon'],
        'cover': amazon_cover("B0H9NQRB56"),
        'summary': 'Isaiah, Patch, and a blue scarf carry a tender story about grief, memory, and helping another child heal.',
        'description': "The Storybook Edition presents Isaiah and Patch's complete healing journey in a classic black-and-white format for young readers and families.",
        'author_note': 'Love can be carried forward, even after loss. — Will Scott',
        'amazon_link': 'https://www.amazon.com/dp/B0H9NQRB56',
        'trailer_url': '',
        'status': 'new',
        'series_order': 2,
        'reviews': [],
        'related': ['let-it-go-little-doll', 'let-it-go-little-bear-deluxe'],
    },
    {
        'id': 'let-it-go-little-bear-deluxe',
        'title': 'Let It Go, Little Bear',
        'subtitle': 'Deluxe Watercolor Edition — Premium Color',
        'category': "Children's Books",
        'categories': ["Children's Books", 'Emotional Healing', 'The Let It Go Series'],
        'price': 0.0,
        'formats': ['Paperback', 'Premium Color', 'Amazon'],
        'cover': amazon_cover("B0H9P6BZZN"),
        'summary': 'Isaiah, Patch, and a blue scarf carry a tender story about grief, memory, and helping another child heal.',
        'description': 'The Deluxe Watercolor Edition pairs the complete story with a premium-color presentation created for families, gifts, and collectors.',
        'author_note': 'Love can be carried forward, even after loss. — Will Scott',
        'amazon_link': 'https://www.amazon.com/dp/B0H9P6BZZN',
        'trailer_url': '',
        'status': 'new',
        'series_order': 2,
        'reviews': [],
        'related': ['let-it-go-little-doll', 'let-it-go-little-bear'],
    },
    {
        'id': 'unhappy',
        'title': 'UNHAPPY',
        'subtitle': "Rock Bottom Wasn't the End. It Was the Beginning.",
        'category': 'Coming Soon',
        'categories': ['Healing & Personal Growth', 'Coming Soon'],
        'price': 0.0,
        'formats': [],
        'cover': 'https://static.prod-images.emergentagent.com/jobs/7463b3a3-ce4d-4fcb-8b80-776d01ad6286/images/23adcf7c12c78994f8d4ad5f94abe519615112fd6766b835b5284d03486dddf9.png',
        'summary': 'An honest book for people at rock bottom who are not ready for fake positivity—but are still looking for a way forward.',
        'description': 'In development. The manuscript will remain marked Coming Soon until it is truly finished.',
        'author_note': 'Rock bottom is a place, not a permanent address. — Will Scott',
        'amazon_link': '',
        'trailer_url': '',
        'status': 'coming_soon',
        'reviews': [],
        'related': ['the-storm-in-me', 'quiet-battles'],
    },
]


BOOK_CATEGORIES = [
    "Healing & Personal Growth",
    "Faith & Encouragement",
    "Career & Life",
    "Children's Books",
    "The Let It Go Series",
    "Science Fiction",
    "The Last Block on Earth Series",
    "The Abductee Chronicles",
    "Coming Soon",
]
