"""Seed content for StormAndMeOfficial. Imported by server.py on startup (idempotent)."""

IMG = {
    "logo": "https://static.prod-images.emergentagent.com/jobs/7463b3a3-ce4d-4fcb-8b80-776d01ad6286/images/a3d5a538ff81f998f6794bf45162190a817187cbc7de2e5721dad88e66e09e8f.png",
    "hero": "https://static.prod-images.emergentagent.com/jobs/7463b3a3-ce4d-4fcb-8b80-776d01ad6286/images/775346fa723f1ad9cd453640a09247622a64e34e471f2f9bf6cb08fb58715a0d.png",
    "portrait": "https://static.prod-images.emergentagent.com/jobs/7463b3a3-ce4d-4fcb-8b80-776d01ad6286/images/2df0c455129892f105f317e3f6900db0643310294f8eaa82eb3eb6e1433030f0.png",
    "book_doll": "https://static.prod-images.emergentagent.com/jobs/7463b3a3-ce4d-4fcb-8b80-776d01ad6286/images/c2910f5ab4ed356f584dab9c7e6675d4801bac7846e61dcb39fd8fe556362641.png",
    "book_bear": "https://static.prod-images.emergentagent.com/jobs/7463b3a3-ce4d-4fcb-8b80-776d01ad6286/images/5ba192991957095a9a2e23484df8aa269daba22c1d2625da181cf3ebca9dd183.png",
    "book_layoff": "https://static.prod-images.emergentagent.com/jobs/7463b3a3-ce4d-4fcb-8b80-776d01ad6286/images/be20f500ea59ce81a260700eb16cc96686eb600c262dbd0b097cd0c05536ed74.png",
    "book_unhappy": "https://static.prod-images.emergentagent.com/jobs/7463b3a3-ce4d-4fcb-8b80-776d01ad6286/images/23adcf7c12c78994f8d4ad5f94abe519615112fd6766b835b5284d03486dddf9.png",
    "album": "https://static.prod-images.emergentagent.com/jobs/7463b3a3-ce4d-4fcb-8b80-776d01ad6286/images/fbf611a2b6c7217d724b55994d90923fcfb5357d4369272d7a66fabacd917668.png",
    "book_generic1": "https://images.unsplash.com/photo-1529521818954-c76995518833",
    "book_generic2": "https://images.unsplash.com/photo-1662152331050-48cb83a01ab6",
    "hoodie": "https://images.unsplash.com/photo-1680292783974-a9a336c10366?crop=entropy&cs=srgb&fm=jpg&q=85",
    "tshirt": "https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "mug": "https://images.unsplash.com/photo-1518358246973-95637f1df901",
    "mic": "https://images.pexels.com/photos/10933688/pexels-photo-10933688.jpeg",
    "mic_alt": "https://images.pexels.com/photos/7301210/pexels-photo-7301210.jpeg",
    "portrait_alt": "https://images.pexels.com/photos/13000444/pexels-photo-13000444.jpeg",
    "music_moody": "https://images.pexels.com/photos/28003184/pexels-photo-28003184.jpeg",
}

REVIEWS = [
    {"name": "Danielle R.", "rating": 5, "text": "I felt like someone finally understood the season I was in. Read it in one sitting."},
    {"name": "Marcus T.", "rating": 5, "text": "Honest, hopeful, and never preachy. Gave a copy to my brother."},
    {"name": "Anonymous", "rating": 4, "text": "Comforting and real. The kind of book you keep on the nightstand."},
]

BOOKS = [
    {
        "id": "let-it-go-little-doll",
        "title": "Let It Go, Little Doll",
        "subtitle": "A gentle story about releasing what hurts",
        "category": "Children's Books",
        "categories": ["Children's Books", "Emotional Healing", "New Releases"],
        "price": 14.99,
        "formats": ["Paperback", "Hardcover", "Ebook"],
        "cover": IMG["book_doll"],
        "summary": "A little doll learns that she doesn't have to carry every heavy feeling by herself.",
        "description": "Part of the Let It Go children's emotional healing series, Let It Go, Little Doll gently walks young readers through big feelings\u2014sadness, worry, and letting go\u2014using soft rain, warm light, and a friend who understands. A comforting bedtime read for children learning that it's okay to feel, and okay to release.",
        "author_note": "I wrote this for every child who feels too much and doesn't have the words yet. \u2014 Willy Will",
        "amazon_link": "https://www.amazon.com/",
        "trailer_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "status": "new",
        "reviews": REVIEWS,
        "related": ["let-it-go-little-bear", "unhappy"],
    },
    {
        "id": "let-it-go-little-bear",
        "title": "Let It Go, Little Bear",
        "subtitle": "Even the bravest bears need to let go",
        "category": "Children's Books",
        "categories": ["Children's Books", "Emotional Healing"],
        "price": 14.99,
        "formats": ["Paperback", "Hardcover", "Ebook"],
        "cover": IMG["book_bear"],
        "summary": "Little Bear discovers that being strong also means knowing when to put the heavy things down.",
        "description": "The second story in the Let It Go series follows Little Bear through a stormy day and a tender lesson: courage isn't carrying everything alone. Warm, rhythmic, and reassuring, it's a favorite for calming bedtime routines.",
        "author_note": "Little Bear is the part of all of us that thinks we have to hold it together. \u2014 Willy Will",
        "amazon_link": "https://www.amazon.com/",
        "trailer_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "status": "available",
        "reviews": REVIEWS,
        "related": ["let-it-go-little-doll", "the-layoff-i-needed"],
    },
    {
        "id": "the-layoff-i-needed",
        "title": "The Layoff I Needed",
        "subtitle": "How losing the job gave me back my life",
        "category": "Career and Life",
        "categories": ["Career and Life", "Personal Growth", "Inspirational"],
        "price": 18.99,
        "formats": ["Paperback", "Ebook", "Audiobook"],
        "cover": IMG["book_layoff"],
        "summary": "The email that ended a career turned out to be the beginning of a life.",
        "description": "A raw, funny, and ultimately hopeful memoir about being laid off and discovering the identity that was buried under the title. The Layoff I Needed is for anyone who has been told they were 'let go' and is quietly wondering what they were being let go toward.",
        "author_note": "The worst day on paper became the best turn in my story. \u2014 Willy Will",
        "amazon_link": "https://www.amazon.com/",
        "trailer_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "status": "available",
        "reviews": REVIEWS,
        "related": ["unhappy", "let-it-go-little-bear"],
    },
    {
        "id": "unhappy",
        "title": "UNHAPPY",
        "subtitle": "Rock Bottom Wasn't the End. It Was the Beginning.",
        "category": "Personal Growth",
        "categories": ["Personal Growth", "Faith and Perseverance", "Inspirational"],
        "price": 19.99,
        "formats": ["Paperback", "Hardcover", "Ebook", "Audiobook"],
        "cover": IMG["book_unhappy"],
        "summary": "A field guide for the people standing at the bottom of the stairs, looking up.",
        "description": "UNHAPPY is an honest look at the season nobody posts about\u2014the bottom. Through short, powerful chapters, Willy Will shares what he learned climbing out: that rock bottom is real, but it is not the address you have to stay at. Practical, faith-friendly, and deeply human.",
        "author_note": "I wrote the book I needed on my worst night. \u2014 Willy Will",
        "amazon_link": "https://www.amazon.com/",
        "trailer_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "status": "available",
        "reviews": REVIEWS,
        "related": ["the-layoff-i-needed", "still-standing"],
    },
    {
        "id": "still-standing",
        "title": "Still Standing",
        "subtitle": "Notes from the other side of the storm",
        "category": "Faith and Perseverance",
        "categories": ["Faith and Perseverance", "Inspirational"],
        "price": 16.99,
        "formats": ["Paperback", "Ebook"],
        "cover": IMG["book_generic1"],
        "summary": "Short reflections for the days you're proud just to still be here.",
        "description": "A collection of meditations on survival, faith, and slow healing. Perfect for morning readings or hard evenings.",
        "author_note": "Some days, still standing is the whole victory. \u2014 Willy Will",
        "amazon_link": "https://www.amazon.com/",
        "trailer_url": "",
        "status": "available",
        "reviews": REVIEWS,
        "related": ["unhappy", "the-quiet-comeback"],
    },
    {
        "id": "the-quiet-comeback",
        "title": "The Quiet Comeback",
        "subtitle": "Rebuilding without an audience",
        "category": "Inspirational",
        "categories": ["Inspirational", "Personal Growth"],
        "price": 17.99,
        "formats": ["Paperback", "Ebook"],
        "cover": IMG["book_generic2"],
        "summary": "The most important comebacks happen where no one is watching.",
        "description": "A book about the unglamorous, unposted work of starting over\u2014one small, faithful choice at a time.",
        "author_note": "Comebacks are built in the quiet. \u2014 Willy Will",
        "amazon_link": "https://www.amazon.com/",
        "trailer_url": "",
        "status": "available",
        "reviews": REVIEWS,
        "related": ["still-standing", "unhappy"],
    },
    {
        "id": "storm-season",
        "title": "Storm Season",
        "subtitle": "A novel",
        "category": "Fiction",
        "categories": ["Fiction"],
        "price": 21.99,
        "formats": ["Paperback", "Ebook"],
        "cover": IMG["book_generic1"],
        "summary": "When the power goes out for a week, a divided family learns to hear each other again.",
        "description": "Willy Will's debut novel\u2014an intimate, atmospheric story set during one long storm that forces four people under one roof to finally say what they mean.",
        "author_note": "My first fiction. It scared me. That's how I knew to write it. \u2014 Willy Will",
        "amazon_link": "https://www.amazon.com/",
        "trailer_url": "",
        "status": "coming_soon",
        "reviews": [],
        "related": ["unhappy", "still-standing"],
    },
    {
        "id": "let-it-go-little-light",
        "title": "Let It Go, Little Light",
        "subtitle": "The next chapter in the healing series",
        "category": "Children's Books",
        "categories": ["Children's Books", "Emotional Healing", "Coming Soon"],
        "price": 14.99,
        "formats": ["Paperback", "Hardcover"],
        "cover": IMG["book_doll"],
        "summary": "A tiny light learns that shining is allowed, even after a dark night.",
        "description": "The upcoming third book in the beloved Let It Go series. Sign up to the family to be first to know when it releases.",
        "author_note": "Coming soon. \u2014 Willy Will",
        "amazon_link": "",
        "trailer_url": "",
        "status": "coming_soon",
        "reviews": [],
        "related": ["let-it-go-little-doll", "let-it-go-little-bear"],
    },
]

BOOK_CATEGORIES = [
    "Children's Books", "Emotional Healing", "Inspirational", "Personal Growth",
    "Career and Life", "Faith and Perseverance", "Fiction", "New Releases", "Coming Soon",
]

MUSIC = [
    {
        "id": "storm-and-soul",
        "type": "album",
        "title": "Storm & Soul",
        "artist": "Willy Will",
        "release_date": "2026-03-01",
        "cover": IMG["album"],
        "description": "A ten-track journey through love, faith, regret, and getting back up. Recorded in the middle of the season it describes.",
        "story": "I made most of this album on nights I couldn't sleep. Every song is a conversation I couldn't have out loud.",
        "audio_preview": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "lyrics": "",
        "streaming": {"spotify": "#", "apple": "#", "youtube_music": "#", "amazon_music": "#", "youtube": "#", "tiktok": "#"},
        "video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "status": "new",
    },
    {
        "id": "still-here-single",
        "type": "single",
        "title": "Still Here",
        "artist": "Willy Will",
        "release_date": "2026-02-14",
        "cover": IMG["music_moody"],
        "description": "The lead single. A quiet anthem for anyone who almost gave up and didn't.",
        "story": "I wrote 'Still Here' the morning after the hardest night. It's the most honest thing I've recorded.",
        "audio_preview": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
        "lyrics": "Verse 1...\nI'm still here, still here...",
        "streaming": {"spotify": "#", "apple": "#", "youtube_music": "#", "amazon_music": "#", "youtube": "#", "tiktok": "#"},
        "video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "status": "new",
    },
    {
        "id": "rock-bottom",
        "type": "single",
        "title": "Rock Bottom (Beginning)",
        "artist": "Willy Will",
        "release_date": "2026-01-10",
        "cover": IMG["mic"],
        "description": "A companion song to the book UNHAPPY.",
        "story": "This one is for the people at the bottom of the stairs.",
        "audio_preview": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
        "lyrics": "",
        "streaming": {"spotify": "#", "apple": "#", "youtube_music": "#", "amazon_music": "#", "youtube": "#", "tiktok": "#"},
        "video_url": "",
        "status": "available",
    },
    {
        "id": "let-it-go-song",
        "type": "single",
        "title": "Let It Go",
        "artist": "Willy Will",
        "release_date": "2025-11-20",
        "cover": IMG["mic_alt"],
        "description": "The song that started the whole Let It Go series.",
        "story": "Before it was a children's book, it was a lullaby I hummed to myself.",
        "audio_preview": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
        "lyrics": "",
        "streaming": {"spotify": "#", "apple": "#", "youtube_music": "#", "amazon_music": "#", "youtube": "#", "tiktok": "#"},
        "video_url": "",
        "status": "available",
    },
]

VIDEOS = [
    {"id": "v1", "title": "Still Here \u2014 Official Music Video", "type": "Music Videos", "youtube_id": "dQw4w9WgXcQ", "thumbnail": IMG["music_moody"], "featured": True, "description": "The official video for the lead single."},
    {"id": "v2", "title": "UNHAPPY \u2014 Book Trailer", "type": "Book Trailers", "youtube_id": "dQw4w9WgXcQ", "thumbnail": IMG["book_unhappy"], "featured": False, "description": "A cinematic look inside the book."},
    {"id": "v3", "title": "The Story Behind the Storm", "type": "Behind-the-Scenes", "youtube_id": "dQw4w9WgXcQ", "thumbnail": IMG["hero"], "featured": False, "description": "Where the brand began."},
    {"id": "v4", "title": "Let It Go \u2014 Lyric Video", "type": "Lyric Videos", "youtube_id": "dQw4w9WgXcQ", "thumbnail": IMG["mic_alt"], "featured": False, "description": "Sing along."},
    {"id": "v5", "title": "Studio Session: Storm & Soul", "type": "Behind-the-Scenes", "youtube_id": "dQw4w9WgXcQ", "thumbnail": IMG["mic"], "featured": False, "description": "Making the album."},
    {"id": "v6", "title": "A Message for Anyone in the Rain", "type": "Personal Messages", "youtube_id": "dQw4w9WgXcQ", "thumbnail": IMG["portrait_alt"], "featured": False, "description": "A short, honest message."},
]

PRODUCTS = [
    {
        "id": "storm-hoodie",
        "name": "I Made It Through the Storm Hoodie",
        "category": "Clothing",
        "categories": ["Clothing", "New Arrivals"],
        "price": 54.00,
        "sale_price": 44.00,
        "image": IMG["hoodie"],
        "images": [IMG["hoodie"]],
        "description": "Heavyweight fleece hoodie with the 'I Made It Through the Storm' embroidery. Soft-white on charcoal.",
        "sizes": ["S", "M", "L", "XL", "2XL"],
        "colors": ["Charcoal", "Navy"],
    },
    {
        "id": "still-here-tee",
        "name": "Still Here Tee",
        "category": "Clothing",
        "categories": ["Clothing", "New Arrivals"],
        "price": 28.00,
        "sale_price": None,
        "image": IMG["tshirt"],
        "images": [IMG["tshirt"]],
        "description": "Premium ringspun cotton tee. Minimal 'Still Here' print. Wear the reminder.",
        "sizes": ["S", "M", "L", "XL", "2XL"],
        "colors": ["Black", "Storm Gray"],
    },
    {
        "id": "storm-mug",
        "name": "The Storm Doesn't Get the Final Word Mug",
        "category": "Home and Office",
        "categories": ["Home and Office"],
        "price": 18.00,
        "sale_price": None,
        "image": IMG["mug"],
        "images": [IMG["mug"]],
        "description": "Matte black 12oz mug with the brand line in silver. For slow, honest mornings.",
        "sizes": ["One Size"],
        "colors": ["Matte Black"],
    },
    {
        "id": "create-through-rain-tee",
        "name": "Create Through the Rain Tee",
        "category": "Clothing",
        "categories": ["Clothing"],
        "price": 28.00,
        "sale_price": None,
        "image": IMG["tshirt"],
        "images": [IMG["tshirt"]],
        "description": "For the makers who don't wait for the sky to clear.",
        "sizes": ["S", "M", "L", "XL"],
        "colors": ["Black"],
    },
    {
        "id": "unhappy-signed-book",
        "name": "UNHAPPY \u2014 Signed Paperback",
        "category": "Books",
        "categories": ["Books", "Limited Edition"],
        "price": 29.99,
        "sale_price": None,
        "image": IMG["book_unhappy"],
        "images": [IMG["book_unhappy"]],
        "description": "A limited run of signed paperbacks of UNHAPPY, personalized by Willy Will.",
        "sizes": ["One Size"],
        "colors": ["Paperback"],
    },
    {
        "id": "storm-soul-bundle",
        "name": "Storm & Soul Music + Tee Bundle",
        "category": "Bundles",
        "categories": ["Bundles", "Music"],
        "price": 45.00,
        "sale_price": 39.00,
        "image": IMG["album"],
        "images": [IMG["album"]],
        "description": "Digital download of the Storm & Soul album plus the Still Here tee. Save when you bundle.",
        "sizes": ["S", "M", "L", "XL"],
        "colors": ["Black"],
    },
    {
        "id": "let-it-go-journal",
        "name": "Let It Go Journal",
        "category": "Home and Office",
        "categories": ["Home and Office", "Accessories"],
        "price": 22.00,
        "sale_price": None,
        "image": IMG["book_generic2"],
        "images": [IMG["book_generic2"]],
        "description": "A guided journal with prompts drawn from the Let It Go series. Lay-flat binding, soft-white pages.",
        "sizes": ["One Size"],
        "colors": ["Navy"],
    },
    {
        "id": "storm-tote",
        "name": "Storm & Me Official Tote",
        "category": "Accessories",
        "categories": ["Accessories", "New Arrivals"],
        "price": 20.00,
        "sale_price": None,
        "image": IMG["hoodie"],
        "images": [IMG["hoodie"]],
        "description": "Heavy canvas tote with the STORM & ME OFFICIAL mark. Built for books.",
        "sizes": ["One Size"],
        "colors": ["Natural", "Black"],
    },
]

PRODUCT_CATEGORIES = ["Clothing", "Books", "Music", "Home and Office", "Accessories", "Limited Edition", "Bundles", "New Arrivals"]

POSTS = [
    {"id": "welcome", "title": "Welcome to StormAndMeOfficial", "date": "2026-06-01", "category": "Personal Updates", "image": IMG["hero"], "preview": "This is the official home of everything I'm building\u2014books, music, videos, and merch born in the storm.", "content": "For a long time I created quietly. This site is me deciding to build in the open. Welcome to the family."},
    {"id": "still-here-out-now", "title": "\u201cStill Here\u201d Is Out Now", "date": "2026-05-20", "category": "Music Releases", "image": IMG["music_moody"], "preview": "The lead single from Storm & Soul is officially everywhere you stream music.", "content": "I wrote this song the morning after the hardest night. Thank you for listening."},
    {"id": "unhappy-launch", "title": "UNHAPPY Is Available Everywhere", "date": "2026-05-01", "category": "New Book Announcements", "image": IMG["book_unhappy"], "preview": "Rock bottom wasn't the end. It was the beginning. The new book is here.", "content": "This is the book I needed on my worst night. I hope it finds the people who need it too."},
    {"id": "merch-drop", "title": "The Storm Collection Has Landed", "date": "2026-04-15", "category": "Merchandise Launches", "image": IMG["hoodie"], "preview": "Wearable reminders that the storm doesn't get the final word.", "content": "New hoodies, tees, and more in the shop. Limited runs on the signed items."},
]

FAQS = [
    {"q": "Who is Willy Will?", "a": "An author, songwriter, storyteller, content creator, and technology professional who makes books and music for people navigating real life."},
    {"q": "Where can I buy the books?", "a": "Directly here on StormAndMeOfficial.com, and on Amazon and other retailers where linked on each book page."},
    {"q": "What formats are the books available in?", "a": "Most titles are available in paperback and ebook, with select titles in hardcover and audiobook."},
    {"q": "How does shipping work?", "a": "Physical merchandise and print books ship within 3\u20135 business days. See our Shipping Policy for details."},
    {"q": "Can I return an item?", "a": "Yes\u2014see our Returns & Refund Policy. Signed and limited-edition items are final sale."},
    {"q": "Is my payment secure?", "a": "Absolutely. Checkout is handled securely by Stripe. We never store your card details."},
    {"q": "How do I follow new releases?", "a": "Join the family newsletter and subscribe to the official music channel for first access."},
]
